config/routes.rb
Rails.application.routes.draw do
  root 'application#intro'

  get 'staff/new'
  resources :staff
  #root 'staff#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/staff.rb
class Staff < ApplicationRecord

  validates :name, presence: true
  validates :age, presence: true, numericality: {:greater_than => 0}
  validates :designation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def intro
    render html: "Hello this is a Welcome page of CRUD App. "
  end

end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  def index
    @staff = Staff.all
  end

  def show
    @staff = Staff.find(params[:id])
  end

  def new
    @staff = Staff.new
  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def create
    @staff = Staff.new(staff_params)

    if @staff.save
      redirect_to @staff
    else
      render 'new'
    end
  end

  def update
    @staff = Staff.find(params[:id])

    if @staff.update(staff_params)
      redirect_to @staff
    else
      render 'edit'
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy

    redirect_to controller: 'staff'
  end

  private
    def staff_params
      params.require(:staff).permit(:name, :age, :gender, :designation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/staff/edit.html.erb
<h1>Edit Staff Details</h1>

<%= form_with(model: @staff, local: true) do |form| %>

  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@staff.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @staff.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :Age %><br>
    <%= form.text_field :age %>
  </p>

  <p>
    <%= form.label :Gender %><br>
    <%= form.text_field :gender %>
  </p>

  <p>
    <%= form.label :Designation %><br>
    <%= form.text_field :designation %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<td><%= link_to 'Back', staff_path(@staff) %></td>

app/views/staff/index.html.erb
<h1>Staff List</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Designation</th>
    <th colspan="4"></th>
  </tr>

  <% @staff.each do |staff| %>
    <tr>
      <td><%= staff.name %></td>
      <td><%= staff.designation %></td>
      <td><%= link_to 'Details', staff_path(staff) %></td>
      <td>&nbsp&nbsp&nbsp</td>
      <td><%= link_to 'Delete', staff_path(staff),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<p>=========================================== </p>
<br>
<div>
<p> Click the below link to enter new staff details </p>
<%= link_to 'Create', new_staff_path %>
</div>

app/views/staff/new.html.erb
<h1>New Employees Form </h1>


<%= form_for @staff, url: {:action=>"create"} do |form| %>

  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@staff.errors.count, "error") %> prohibited
        this entry from being saved:
      </h2>
      <ul>
        <% @staff.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :Age %><br>
    <%= form.text_field :age %>
  </p>

  <p>
    <%= form.label :Gender %><br>
    <%= form.text_field :gender %>
  </p>

  <p>
    <%= form.label :Designation %><br>
    <%= form.text_field :designation %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', controller: 'staff' %>

app/views/staff/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @staff.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @staff.gender %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @staff.designation %>
</p>

<p>
  <%= link_to 'Edit', edit_staff_path(@staff) %> &nbsp &nbsp
  <%= link_to 'Back', controller: 'staff' %>
</p>